### ISSUE TITLE
It didn't work when scrub is false in NextJs.

### ISSUE THREAD

**Issue by d3adrabbit** [basementstudio/scrollytelling#41]
It  didn't work when scrub is false in NextJs.

https://codesandbox.io/p/sandbox/frosty-lumiere-kc2vc2?file=%2Fapp%2Fpage.tsx%3A10%2C11-10%2C22

<img width="1512" alt="截屏2023-08-13 22 50 24" src="https://github.com/basementstudio/scrollytelling/assets/49115041/2af9efb3-11b7-4863-ae8c-14d793aa277a">

**Comment by liho00** [comment]
> It didn't work when scrub is false in NextJs.
> 
> https://codesandbox.io/p/sandbox/frosty-lumiere-kc2vc2?file=%2Fapp%2Fpage.tsx%3A10%2C11-10%2C22
> 
> <img alt="截屏2023-08-13 22 50 24" width="1512" src="https://user-images.githubusercontent.com/49115041/260310229-2af9efb3-11b7-4863-ae8c-14d793aa277a.png">

I think you missing the from,

try put 
```
start: 0,
end: 100,
from: {
scale: 1
}
to: {
scale: 2
}
```
or can refer to the example website https://github.com/basementstudio/scrollytelling/tree/main/website

**Comment by d3adrabbit** [comment]
There seems to be a problem with the `toogleActions`. 

Maybe `toggleActions` should be `play none none none` by default.

https://github.com/basementstudio/scrollytelling/blob/139a77eccee5fa88ab824d82e057ca6f00ed5928/scrollytelling/src/primitive.tsx#L37C16-L37C16

**Comment by julianbenegas** [comment]
hey @d3adrabbit, you can override `toogleActions` by passing it via prop. And the default should be `play none none none` as it comes from GSAP.

<img width="827" alt="CleanShot 2023-10-31 at 09 38 09 png" src="https://github.com/basementstudio/scrollytelling/assets/40034115/39f06d15-9b86-4ddd-99d7-2ed3f3f6e857">
