### ISSUE TITLE
onRefresh callback is not stable

### ISSUE THREAD

**Issue by liho00** [basementstudio/scrollytelling#47]
```
 <Scrollytelling.Root
      scrub={0.75}
      callbacks={{
        onRefresh: () => {
          console.log("refresh", progress.value); // most of the time return `refresh 0` as screenshot below
          update(progress.value);
        },
      }}
    >
 ```

<img width="394" alt="image" src="https://github.com/basementstudio/scrollytelling/assets/77238199/5f110df1-3499-4b5c-852f-fc1d4efb952f">

**Comment by julianbenegas** [comment]
hey @liho00, from the [GSAP docs](https://greensock.com/docs/v3/Plugins/ScrollTrigger#:~:text=%2C%20isActive)-,onRefresh,-Function%20%2D%20A%20callback):

> `onRefresh`: A callback for when the a refresh occurs (typically a resize event) which forces the ScrollTrigger to recalculate all of its positioning.

Is this what you want? You may be looking for `onUpdate`.
