### ISSUE TITLE
Horizontal scrolling - issue

### ISSUE THREAD

**Issue by Pfurr** [basementstudio/scrollytelling#63]
Hello everyone, could someone please explain if it is also possible to create horizontal scrooling?

I have created a horizontal scrooling with standard gsap, but I can't figure out how to do it on scrollytelling. Thank you.

Here is the code I am using with gsap without scrollytelling (next js, tailwind):

![code](https://github.com/basementstudio/scrollytelling/assets/26284332/14b853a4-3aff-4e54-a50d-5cfc8e0bf06f)

**Comment by nazarenooviedo** [comment]
Hey @Pfurr how is going?  sorry about the response delay, I leave here an example to reproduce the same request that you need. https://github.com/basementstudio/scrollytelling/pull/64

I hope that works for you.
